### ISSUE TITLE
Set up CI for SYCL code

### ISSUE THREAD

**Issue by tkoskela** [UCL/openqcd-oneapi#11]

**Comment by tkoskela** [comment]
We could store the data sets on zenodo (like figshare). @JamieJQuinn and @ageorgou used this for larger test datasets for TROVE. This worked really well, allowed versioning of datasets. The datasets can be downloaded through the zenodo API (see https://github.com/Trovemaster/TROVE/blob/feature/unit-testing/test/regression/download_benchmarks.sh for an example). Didn't get round to caching in GHA but others have pointed to the cache action which is fab. Only problem we found with zenodo is it's really hard for multiple users to "own" a dataset so collaboration is tricky.

The size limit is 50Gb per dataset

**Comment by krishnakumarg1984** [comment]
Ah. That reminds me of a few other options:

 - [mendeley datasets](https://data.mendeley.com/)
 - [EOSC cloud/EOSC hub](https://eosc-portal.eu/)
 - [figshare](https://figshare.com/)
 - [dataverse](https://dataverse.org/)

**Comment by tkoskela** [comment]
I've pushed the smaller `*-16-16-16-16` and `*-32-32-32-32` files to the repo via [git lfs](https://git-lfs.github.com/). I think those will suffice for some simple CI.
