### ISSUE TITLE
Compile generated sycl code with computecpp

### ISSUE THREAD

**Issue by tkoskela** [UCL/openqcd-oneapi#5]

**Comment by tkoskela** [comment]
Not clear how well USM is supported. This needs to be investigated.

**Comment by krishnakumarg1984** [comment]
Experimental support for SYCL2020 USM spec added a few releases ago. Still marked experimental: https://support.codeplay.com/t/dose-computecpp-support-usm/413

**Comment by tkoskela** [comment]
Confirmed USM is not supported. Results in unreadable error messages.

Computecpp only supports 1.3.1 standard officially. We don't want to regress our code to that.
